name: sipgn
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  auto_route: ^10.2.0
  bloc: ^9.0.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  injectable: ^2.5.2
  intl: ^0.20.2
  shared_preferences: ^2.3.2

dev_dependencies:
  auto_route_generator: ^10.2.5
  bloc_test: ^10.0.0
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  mocktail: ^1.0.4
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
